ùapiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
        name: pacman
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: rg.fr-par.scw.cloud/ilkilabs/pacman:v1
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
